<script lang="ts">
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle
	} from '$lib/components/ui/card';
	import { Tabs, TabsContent, TabsList, TabsTrigger } from '$lib/components/ui/tabs';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Alert, AlertDescription } from '$lib/components/ui/alert';
	import Terminal from './Terminal.svelte';
	import OutputList from './OutputList.svelte';
	import CodeBlock from './CodeBlock.svelte';
	import {
		Terminal as TerminalIcon,
		FileOutput,
		TriangleAlert,
		Code,
		ExternalLink,
		BracesIcon
	} from '@lucide/svelte';
	import { createPythonStaticCallFromConfig } from '$lib/services/execution/pythonCodeGen';

	interface OutputEntry {
		keyPath: (string | number)[];
		filePath: string;
		pythonAccessor: string;
		title: string | null;
		description: string | null;
		isRoot: boolean;
	}

	interface Props {
		commandArgs: string[];
		outputEntries: OutputEntry[];
		descriptorConfig: object;
		niwrapError: string | null;
		hasConfig: boolean;
		githubUrls: { schemaInput: string; descriptor: string };
		isMobile?: boolean;
		activeTab?: string;
	}

	let {
		commandArgs,
		outputEntries,
		descriptorConfig,
		niwrapError,
		hasConfig,
		githubUrls,
		isMobile = false,
		activeTab = $bindable('command')
	}: Props = $props();

	const fileCount = $derived(outputEntries.filter((e) => !e.isRoot).length);
	const hasOutputs = $derived(outputEntries.length > 0);

	let pythonCode = $state<string | null>(null);
	let pythonCodeError = $state<Error | null>(null);
	$effect(() => {
		pythonCodeError = null;

		createPythonStaticCallFromConfig(descriptorConfig)
			.then((code) => {
				pythonCode = code;
			})
			.catch((error) => {
				pythonCodeError = error;
			});
	});

	function openGithubFile(url: string) {
		window.open(url, '_blank', 'noopener,noreferrer');
	}
</script>

<div class="space-y-6">
	{#if !isMobile}
		<header class="space-y-2">
			<div class="flex items-center justify-between">
				<div>
					<h2 class="text-xl font-semibold tracking-tight text-foreground">Results</h2>
					<p class="text-sm text-muted-foreground">Generated command and outputs</p>
				</div>
			</div>
		</header>
	{/if}

	<Tabs bind:value={activeTab} class="w-full">
		<TabsList class="grid w-full grid-cols-4">
			<TabsTrigger value="command" disabled={!hasConfig} class="flex items-center gap-2">
				<TerminalIcon class="h-3 w-3" />
				<span class:hidden={isMobile} class="xl:inline">Command</span>
			</TabsTrigger>
			<TabsTrigger value="outputs" disabled={!hasOutputs} class="flex items-center gap-2">
				<FileOutput class="h-3 w-3" />
				<span class:hidden={isMobile} class="xl:inline">Outputs</span>
				{#if fileCount > 0}
					<Badge variant="secondary" class="ml-1 h-4 px-1 text-xs">
						{fileCount}
					</Badge>
				{/if}
			</TabsTrigger>
			<TabsTrigger value="python" disabled={!hasConfig} class="flex items-center gap-2">
				<Code class="h-3 w-3" />
				<span class:hidden={isMobile} class="xl:inline">Python</span>
			</TabsTrigger>
			<TabsTrigger value="config" disabled={!hasConfig} class="flex items-center gap-2">
				<BracesIcon class="h-3 w-3" />
				<span class:hidden={isMobile} class="xl:inline">JSON</span>
			</TabsTrigger>
		</TabsList>

		<TabsContent value="command" class="mt-6">
			<div class="space-y-4">
				{#if niwrapError}
					<Alert variant="destructive">
						<TriangleAlert class="h-4 w-4" />
						<AlertDescription>
							<strong>Configuration Error:</strong>
							{niwrapError}
						</AlertDescription>
					</Alert>
				{/if}
				<Card>
					<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
						<div>
							<CardTitle class="text-base">Generated Command</CardTitle>
							<CardDescription>
								{isMobile
									? 'Copy and run in terminal'
									: 'Copy and run this command in your terminal'}
							</CardDescription>
						</div>
					</CardHeader>
					<CardContent>
						<Terminal args={commandArgs} prompt="$ " showCursor={true} class="font-mono text-sm" />
					</CardContent>
				</Card>
			</div>
		</TabsContent>

		<TabsContent value="outputs" class="mt-6">
			<Card>
				<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
					<div>
						<CardTitle class="text-base">Expected Output Files</CardTitle>
						<CardDescription>
							{isMobile
								? 'Files generated by the command'
								: 'Files that will be generated when you run the command'}
						</CardDescription>
					</div>
					{#if !isMobile}
						<Button
							variant="outline"
							size="sm"
							onclick={() => openGithubFile(githubUrls.descriptor)}
							title="View output schema"
						>
							<ExternalLink class="h-3 w-3" />
						</Button>
					{/if}
				</CardHeader>
				<CardContent>
					<OutputList entries={outputEntries} />
				</CardContent>
			</Card>
		</TabsContent>

		<TabsContent value="python" class="mt-6">
			<Card>
				<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
					<div>
						<CardTitle class="text-base">Python Code</CardTitle>
						<CardDescription>
							{isMobile ? 'This config in Python' : 'Use this config in Python with NiWrap'}
						</CardDescription>
					</div>
				</CardHeader>
				<CardContent>
					{#if pythonCodeError}
						<Alert variant="destructive">
							<TriangleAlert class="h-4 w-4" />
							<AlertDescription>
								<strong>Python Code Generation Error:</strong>
								{pythonCodeError.message}
							</AlertDescription>
						</Alert>
					{:else if pythonCode}
						<CodeBlock code={pythonCode} language="python" />
					{/if}
				</CardContent>
			</Card>
		</TabsContent>

		<TabsContent value="config" class="mt-6">
			<Card>
				<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
					<div>
						<CardTitle class="text-base">Configuration JSON</CardTitle>
						<CardDescription>
							Parameter values in JSON. Can be dynamically executed using <code
								>niwrap.execute(...)</code
							>.
						</CardDescription>
					</div>
					{#if !isMobile}
						<Button
							variant="outline"
							size="sm"
							onclick={() => openGithubFile(githubUrls.schemaInput)}
							title="View input schema"
						>
							<ExternalLink class="h-3 w-3" />
						</Button>
					{/if}
				</CardHeader>
				<CardContent>
					<CodeBlock code={JSON.stringify(descriptorConfig, null, 2)} language="json" />
				</CardContent>
			</Card>
		</TabsContent>
	</Tabs>
</div>
