<script lang="ts">
	import { Tabs, TabsContent, TabsList, TabsTrigger } from '$lib/components/ui/tabs';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Alert, AlertDescription } from '$lib/components/ui/alert';
	import Terminal from './Terminal.svelte';
	import OutputList from './OutputList.svelte';
	import CodeBlock from './CodeBlock.svelte';
	import {
		Terminal as TerminalIcon,
		FileOutput,
		TriangleAlert,
		Code,
		ExternalLink,
		BracesIcon
	} from '@lucide/svelte';
	import { createPythonStaticCallFromConfig } from '$lib/services/execution/pythonCodeGen';

	interface OutputEntry {
		keyPath: (string | number)[];
		filePath: string;
		pythonAccessor: string;
		title: string | null;
		description: string | null;
		isRoot: boolean;
	}

	interface Props {
		commandArgs: string[];
		outputEntries: OutputEntry[];
		descriptorConfig: object;
		niwrapError: string | null;
		hasConfig: boolean;
		githubUrls: { schemaInput: string; descriptor: string };
		isMobile?: boolean;
		activeTab?: string;
	}

	let {
		commandArgs,
		outputEntries,
		descriptorConfig,
		niwrapError,
		hasConfig,
		githubUrls,
		isMobile = false,
		activeTab = $bindable('command')
	}: Props = $props();

	const fileCount = $derived(outputEntries.filter((e) => !e.isRoot).length);
	const hasOutputs = $derived(outputEntries.length > 0);

	let pythonCode = $state<string | null>(null);
	let pythonCodeError = $state<Error | null>(null);
	$effect(() => {
		pythonCodeError = null;

		createPythonStaticCallFromConfig(descriptorConfig)
			.then((code) => {
				pythonCode = code;
			})
			.catch((error) => {
				pythonCodeError = error;
			});
	});

	function openGithubFile(url: string) {
		window.open(url, '_blank', 'noopener,noreferrer');
	}
</script>

<div class="space-y-6">
	<Tabs bind:value={activeTab} class="w-full">
		<TabsList class="grid w-full grid-cols-4">
			<TabsTrigger value="command" disabled={!hasConfig} class="flex items-center gap-2">
				<TerminalIcon class="h-3.5 w-3.5" />
				<span class:hidden={isMobile} class="xl:inline">Command</span>
			</TabsTrigger>
			<TabsTrigger value="outputs" disabled={!hasOutputs} class="flex items-center gap-2">
				<FileOutput class="h-3.5 w-3.5" />
				<span class:hidden={isMobile} class="xl:inline">Outputs</span>
				{#if fileCount > 0}
					<Badge variant="secondary" class="ml-1 h-4 px-1 text-xs">
						{fileCount}
					</Badge>
				{/if}
			</TabsTrigger>
			<TabsTrigger value="python" disabled={!hasConfig} class="flex items-center gap-2">
				<Code class="h-3.5 w-3.5" />
				<span class:hidden={isMobile} class="xl:inline">Python</span>
			</TabsTrigger>
			<TabsTrigger value="config" disabled={!hasConfig} class="flex items-center gap-2">
				<BracesIcon class="h-3.5 w-3.5" />
				<span class:hidden={isMobile} class="xl:inline">JSON</span>
			</TabsTrigger>
		</TabsList>

		<TabsContent value="command" class="mt-4">
			<div class="space-y-4">
				{#if niwrapError}
					<Alert variant="destructive">
						<TriangleAlert class="h-4 w-4" />
						<AlertDescription>
							<strong>Configuration Error:</strong>
							{niwrapError}
						</AlertDescription>
					</Alert>
				{/if}
				<div class="space-y-2">
					<h3 class="text-base font-semibold">Generated Command</h3>
					<p class="text-sm text-muted-foreground">
						{isMobile ? 'Copy and run in terminal' : 'Copy and run this command in your terminal'}
					</p>
				</div>
				<Terminal args={commandArgs} prompt="$ " showCursor={true} class="font-mono text-sm" />
			</div>
		</TabsContent>

		<TabsContent value="outputs" class="mt-4">
			<div class="space-y-4">
				<div class="flex items-center justify-between">
					<div class="space-y-1">
						<h3 class="text-base font-semibold">Expected Output Files</h3>
						<p class="text-sm text-muted-foreground">
							{isMobile
								? 'Files generated by the command'
								: 'Files that will be generated when you run the command'}
						</p>
					</div>
					{#if !isMobile}
						<Button
							variant="outline"
							size="sm"
							onclick={() => openGithubFile(githubUrls.descriptor)}
							title="View output schema"
						>
							<ExternalLink class="h-3 w-3" />
						</Button>
					{/if}
				</div>
				<OutputList entries={outputEntries} />
			</div>
		</TabsContent>

		<TabsContent value="python" class="mt-4">
			<div class="space-y-4">
				<div class="space-y-1">
					<h3 class="text-base font-semibold">Python Code</h3>
					<p class="text-sm text-muted-foreground">
						{isMobile ? 'This config in Python' : 'Use this config in Python with NiWrap'}
					</p>
				</div>
				{#if pythonCodeError}
					<Alert variant="destructive">
						<TriangleAlert class="h-4 w-4" />
						<AlertDescription>
							<strong>Python Code Generation Error:</strong>
							{pythonCodeError.message}
						</AlertDescription>
					</Alert>
				{:else if pythonCode}
					<CodeBlock code={pythonCode} language="python" />
				{/if}
			</div>
		</TabsContent>

		<TabsContent value="config" class="mt-4">
			<div class="space-y-4">
				<div class="flex items-center justify-between">
					<div class="space-y-1">
						<h3 class="text-base font-semibold">Configuration JSON</h3>
						<p class="text-sm text-muted-foreground">
							Parameter values in JSON. Can be dynamically executed using <code
								>niwrap.execute(...)</code
							>.
						</p>
					</div>
					{#if !isMobile}
						<Button
							variant="outline"
							size="sm"
							onclick={() => openGithubFile(githubUrls.schemaInput)}
							title="View input schema"
						>
							<ExternalLink class="h-3 w-3" />
						</Button>
					{/if}
				</div>
				<CodeBlock code={JSON.stringify(descriptorConfig, null, 2)} language="json" />
			</div>
		</TabsContent>
	</Tabs>
</div>
